# Generated by Django 6.0.2 on 2026-02-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('widget_type', models.CharField(choices=[('counter', 'Счётчик'), ('chart_line', 'Линейный график'), ('chart_bar', 'Столбчатая диаграмма'), ('chart_pie', 'Круговая диаграмма'), ('chart_doughnut', 'Кольцевая диаграмма'), ('table', 'Таблица'), ('list', 'Список')], max_length=20, verbose_name='Тип виджета')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('data_source', models.CharField(max_length=50, verbose_name='Источник данных')),
                ('metric', models.CharField(max_length=50, verbose_name='Метрика')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Цвет')),
                ('icon', models.CharField(default='fa-chart-bar', max_length=50, verbose_name='Иконка')),
                ('size', models.CharField(default='col-md-6 col-lg-3', max_length=20, verbose_name='Размер')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('visible_to', models.CharField(blank=True, max_length=20, verbose_name='Показывать для')),
            ],
            options={
                'verbose_name': 'Виджет дашборда',
                'verbose_name_plural': 'Виджеты дашборда',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('login', 'Вход'), ('logout', 'Выход'), ('comment', 'Комментарий'), ('status_change', 'Изменение статуса')], max_length=20, verbose_name='Действие')),
                ('content_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Представление объекта')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('report_type', models.CharField(choices=[('requests', 'Отчёт по заявкам'), ('projects', 'Отчёт по проектам'), ('tasks', 'Отчёт по задачам'), ('users', 'Отчёт по пользователям'), ('financial', 'Финансовый отчёт'), ('custom', 'Пользовательский отчёт')], max_length=20, verbose_name='Тип отчёта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Формат')),
                ('is_scheduled', models.BooleanField(default=False, verbose_name='Запланирован')),
                ('schedule', models.CharField(blank=True, max_length=50, verbose_name='Расписание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
