# Generated by Django 6.0.2 on 2026-02-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('excel', 'Excel (legacy)'), ('csv', 'CSV')], default='xlsx', max_length=10, verbose_name='Формат'),
        ),
    ]
