# Generated by Django 6.0.2 on 2026-02-13 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('outsourcing', 'IT-аутсорсинг'), ('implementation', 'Внедрение ПО'), ('consulting', 'IT-консалтинг'), ('development', 'Разработка ПО'), ('security', 'Информационная безопасность'), ('network', 'Сетевые решения'), ('cloud', 'Облачные сервисы'), ('training', 'Обучение персонала'), ('other', 'Другое')], max_length=50, unique=True, verbose_name='Тип услуги')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_duration_days', models.PositiveIntegerField(default=30, verbose_name='Типовой срок (дней)')),
            ],
            options={
                'verbose_name': 'Шаблон проекта',
                'verbose_name_plural': 'Шаблоны проектов',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Этап')),
                ('stage_type', models.CharField(choices=[('analysis', 'Анализ'), ('backend', 'Backend-разработка'), ('frontend', 'Frontend-разработка'), ('integration', 'Интеграция'), ('testing', 'Тестирование'), ('deploy', 'Внедрение'), ('training', 'Обучение'), ('support', 'Поддержка'), ('consulting', 'Консалтинг'), ('security', 'Аудит безопасности'), ('other', 'Другое')], default='other', max_length=30, verbose_name='Тип этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание работ')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('default_hours', models.DecimalField(decimal_places=1, default=8, max_digits=6, verbose_name='Типовые часы')),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=3000, max_digits=10, verbose_name='Базовая цена за час')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.projecttemplate')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='template_stages', to='core.skill', verbose_name='Нужные навыки')),
            ],
            options={
                'verbose_name': 'Этап шаблона',
                'verbose_name_plural': 'Этапы шаблона',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], default=2, verbose_name='Уровень')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователей',
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
