# Generated by Django 6.0.2 on 2026-02-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('step_type', models.CharField(choices=[('triage', 'Первичный разбор'), ('estimation', 'Оценка'), ('technical', 'Техническое согласование'), ('finance', 'Финансовое согласование'), ('legal', 'Юридическое согласование'), ('client_confirmation', 'Подтверждение клиента')], max_length=40, verbose_name='Тип этапа')),
                ('title', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('rework', 'На доработке')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_request_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='requests_app.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Согласование заявки',
                'verbose_name_plural': 'Согласования заявок',
                'ordering': ['order', 'created_at'],
                'unique_together': {('request', 'order')},
            },
        ),
    ]
