# Generated by Django 6.0.2 on 2026-02-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_requestapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='automation_recommendation',
            field=models.TextField(blank=True, verbose_name='Рекомендации автоматизации'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='number',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Номер заявки'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA срок обработки'),
        ),
    ]
