# Generated by Django 6.0.2 on 2026-02-12 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_servicerequest_automation_recommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок применения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('service_type', models.CharField(blank=True, choices=[('outsourcing', 'IT-аутсорсинг'), ('implementation', 'Внедрение ПО'), ('consulting', 'IT-консалтинг'), ('development', 'Разработка ПО'), ('security', 'Информационная безопасность'), ('network', 'Сетевые решения'), ('cloud', 'Облачные сервисы'), ('training', 'Обучение персонала'), ('other', 'Другое')], max_length=50, verbose_name='Тип услуги')),
                ('priority', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], max_length=20, verbose_name='Приоритет')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Мин. бюджет')),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Макс. бюджет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assign_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules_as_analyst', to=settings.AUTH_USER_MODEL, verbose_name='Назначить аналитика')),
                ('assign_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules_as_executor', to=settings.AUTH_USER_MODEL, verbose_name='Назначить исполнителя')),
            ],
            options={
                'verbose_name': 'Правило маршрутизации заявки',
                'verbose_name_plural': 'Правила маршрутизации заявок',
                'ordering': ['order', 'id'],
            },
        ),
    ]
