# Generated by Django 6.0.2 on 2026-02-12 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_requestroutingrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='deadline_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Напоминание по дедлайну отправлено'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('IN_ANALYSIS', 'Аналитик изучает'), ('ESTIMATION', 'Оценка сроков/бюджета'), ('PROPOSAL_DRAFT', 'Подготовка КП'), ('PROPOSAL_SENT', 'КП отправлено'), ('CLIENT_REVIEW', 'Клиент рассматривает'), ('NEGOTIATION', 'Согласование условий'), ('CLIENT_APPROVED', 'Клиент одобрил'), ('INTERNAL_APPROVAL', 'Внутреннее согласование'), ('LEGAL_REVIEW', 'Юридическая проверка'), ('FINANCIAL_CHECK', 'Финансовый контроль'), ('CONTRACT_DRAFT', 'Подготовка договора'), ('CONTRACT_SENT', 'Договор отправлен'), ('CONTRACT_SIGNED', 'Подписан сторонами'), ('ADVANCE_PAYMENT', 'Поступил аванс'), ('CONVERTED', 'Конвертирован в проект'), ('IN_PROGRESS', 'Работы ведутся'), ('COMPLETED', 'Завершен'), ('REJECTED', 'Отклонен'), ('CANCELLED', 'Отменен клиентом'), ('ARCHIVED', 'В архиве')], default='IN_ANALYSIS', max_length=32, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=32, verbose_name='Было')),
                ('new_status', models.CharField(max_length=32, verbose_name='Стало')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests_app.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История статусов заявки',
                'verbose_name_plural': 'История статусов заявок',
                'ordering': ['-changed_at'],
            },
        ),
    ]
