# Generated by Django 6.0.2 on 2026-02-13 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('requests_app', '0005_servicerequest_deadline_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='clients.clientcompany', verbose_name='Компания клиента'),
        ),
    ]
