# Generated by Django 6.0.2 on 2026-02-13 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Например: ООО «Рога и Копыта»', max_length=200, verbose_name='Краткое наименование')),
                ('full_name', models.CharField(blank=True, help_text='Общество с ограниченной ответственностью «Рога и Копыта»', max_length=400, verbose_name='Полное наименование')),
                ('legal_form', models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП'), ('ao', 'АО'), ('pao', 'ПАО'), ('oao', 'ОАО'), ('zao', 'ЗАО'), ('other', 'Другое')], default='ooo', max_length=10, verbose_name='Орг.-правовая форма')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='Наименование банка')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Кор. счёт')),
                ('settlement_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя')),
                ('director_position', models.CharField(default='Генеральный директор', max_length=100, verbose_name='Должность руководителя')),
                ('director_basis', models.CharField(default='Устава', max_length=100, verbose_name='Действует на основании')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('stamp_image', models.ImageField(blank=True, null=True, upload_to='company_stamps/', verbose_name='Печать (PNG, прозрачный фон)')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='company_signatures/', verbose_name='Подпись руководителя (PNG, прозрачный фон)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец (клиент)')),
            ],
            options={
                'verbose_name': 'Компания клиента',
                'verbose_name_plural': 'Компании клиентов',
                'ordering': ['short_name'],
            },
        ),
    ]
