# Generated by Django 6.0.2 on 2026-02-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0002_requestapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер КП')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('scope', models.TextField(verbose_name='Объём работ')),
                ('assumptions', models.TextField(blank=True, verbose_name='Предположения и ограничения')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итоговая стоимость')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='Срок реализации (дней)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('internal_review', 'Внутреннее согласование'), ('sent', 'Отправлено клиенту'), ('accepted', 'Принято клиентом'), ('rejected', 'Отклонено клиентом')], default='draft', max_length=20, verbose_name='Статус')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действительно до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='requests_app.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=150, verbose_name='Этап')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(default='усл. ед.', max_length=30, verbose_name='Ед. изм.')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.commercialproposal', verbose_name='КП')),
            ],
            options={
                'verbose_name': 'Позиция КП',
                'verbose_name_plural': 'Позиции КП',
                'ordering': ['order', 'id'],
            },
        ),
    ]
