# Generated by Django 6.0.2 on 2026-03-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Планирование'), ('active', 'В работе'), ('on_hold', 'Приостановлен'), ('completed', 'Завершён'), ('archived', 'В архиве'), ('cancelled', 'Отменён')], default='planning', max_length=20, verbose_name='Статус'),
        ),
    ]
