# Generated by Django 6.0.2 on 2026-02-13 11:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_taskassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Часы')),
                ('description', models.TextField(verbose_name='Что сделано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Запись времени',
                'verbose_name_plural': 'Записи времени',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание отчёта')),
                ('hours_total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Затрачено часов')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'На проверке'), ('accepted', 'Принят'), ('revision', 'На доработке')], default='draft', max_length=20, verbose_name='Статус')),
                ('review_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reports', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Отчёт о работе',
                'verbose_name_plural': 'Отчёты о работе',
                'ordering': ['-created_at'],
            },
        ),
    ]
