# Generated by Django 6.0.2 on 2026-02-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('requests_app', '0002_requestapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('subject', models.CharField(max_length=255, verbose_name='Предмет договора')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма договора')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Условия оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('legal_review', 'Юр. согласование'), ('sent', 'Отправлен на подпись'), ('signed', 'Подписан'), ('active', 'Действует'), ('closed', 'Закрыт'), ('terminated', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='proposals.commercialproposal', verbose_name='КП')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='requests_app.servicerequest', verbose_name='Заявка')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
    ]
