# Generated by Django 6.0.2 on 2026-02-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('proposals', '0001_initial'),
        ('requests_app', '0002_requestapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('proposal', 'Коммерческое предложение'), ('contract', 'Договор'), ('act', 'Акт выполненных работ'), ('invoice', 'Счёт на оплату')], max_length=20, verbose_name='Тип документа')),
                ('number', models.CharField(max_length=60, unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Содержимое')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('approved', 'Согласован'), ('signed', 'Подписан'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выставления')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты/подписания')),
                ('file', models.FileField(blank=True, null=True, upload_to='business_documents/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contracts.contract', verbose_name='Договор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_documents', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='proposals.commercialproposal', verbose_name='КП')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_documents', to='requests_app.servicerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Бизнес-документ',
                'verbose_name_plural': 'Бизнес-документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
