# Generated by Django 6.0.2 on 2026-02-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подписания'), ('signed', 'Подписан'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Токен подписания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий подписанта')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено на подписание')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес подписанта')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.businessdocument', verbose_name='Документ')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Подписант')),
            ],
            options={
                'verbose_name': 'Подпись документа',
                'verbose_name_plural': 'Подписи документов',
                'ordering': ['-sent_at'],
                'unique_together': {('document', 'signer')},
            },
        ),
    ]
