# Generated by Django 6.0.2 on 2026-05-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentsignature'),
        ('requests_app', '0006_servicerequest_client_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessdocument',
            unique_together={('request', 'doc_type')},
        ),
    ]
