# Generated by Django 6.0.2 on 2026-02-12 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('analysis', 'Анализ'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('qa', 'Тестирование'), ('deploy', 'Внедрение'), ('support', 'Поддержка')], max_length=30, verbose_name='Этап')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус этапа')),
                ('description', models.TextField(blank=True, verbose_name='Описание этапа')),
                ('planned_start', models.DateField(blank=True, null=True, verbose_name='План старт')),
                ('planned_end', models.DateField(blank=True, null=True, verbose_name='План завершение')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='Факт старт')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Факт завершение')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок этапа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Назначение этапа задачи',
                'verbose_name_plural': 'Назначения этапов задач',
                'ordering': ['order', 'created_at'],
                'unique_together': {('task', 'assignee', 'stage')},
            },
        ),
    ]
